[project]
name = "krug"
version = "0.1.0"
description = "Библиотека для вычисления площади круга и треугольника с GUI и юнит-тестами"
authors = [ { name = "Your Name", email = "your@email.com" } ]
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["krug"] 